### ISSUE TITLE
Radatilly- Reporte General

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#101]
campos a generar:

Fecha | Punto de Venta | Nro. remito | N° de Factura | N° de lote | N° de OC | Razón Social | Destino | Material | Empresa transporte | Grupo | Camión | Chofer | Peso bruto (tn) | Tara (Tn) | Peso neto (tn) | Cant bolsones | importe factura |

y al final

total de remitos
total de bolsones
total de tn
total de kg
total facturado usd
total facturado $

**Comment by sebasmoyano** [comment]
Priorirdad 1

**Comment by sebasmoyano** [comment]
@casma20 Implementado nuevo remito. Se imprime horizontal porque son muchas columnas.
