### ISSUE TITLE
Radatilly - Orden compra

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#104]
me dicen que se han descontado mas toneladas de las normales, puede ser las ordenas anuladas???

**Comment by sebasmoyano** [comment]
Anular remito vuelve a la orden de compra.

**Comment by sebasmoyano** [comment]
Prioridad 3

**Comment by sebasmoyano** [comment]
Arreglado esto Casma. Todos los disponibles fueron recalculados. Ahora todos los remitos basan su cálculo en los remitos existentes. Los movimientos son solo informativos. Cada vez que se modifica un remito por formulario o por acción se re-calcula la orden de compra.
