### ISSUE TITLE
San Fernando - Órdenes - Imprimir  orden de carga

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#11]
cuando se envia a imprimir cualquier orden o guia no sale la impresion en el botn accion. tampoco sise imprime una guia de gobierno da la opcion para imrimirla .
se debe imprimir para el formulario de gobierno orden + guia.
para una orden comun solo la orden.

**Comment by sebasmoyano** [comment]
@casma20 Arreglado. Chequear ahora.

**Comment by sebasmoyano** [comment]
@casma20 cerrando...
