### ISSUE TITLE
Radatilly- Codigo de seguridad

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#113]
Seba acordate de agregarle el codigo de seguridad qeu hablamos a la impresion de los remitos y remitos reumen. 
como tambien el campo de codigo de seguridad en el menu resumen asi lo buscamos 
Habilitar codigo de seguridad en menus de:
Remitos
Remitos Resumen

**Comment by sebasmoyano** [comment]
@casma20 implementado esto.
