### ISSUE TITLE
Radatilly-Facturacion

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#114]
seba cree una factura asociandole remitos y no suma las toneladas ni el importe

![image](https://user-images.githubusercontent.com/38771873/49698837-2219e500-fba8-11e8-9362-6b4c8e9bd014.png)

Despuesw aparece un menu de cheques...fecha de cheques....de donde se carga??? no me sale ninguna opcion para cargar.

![image](https://user-images.githubusercontent.com/38771873/49698851-7624c980-fba8-11e8-8254-16c2ebda6c22.png)

**Comment by sebasmoyano** [comment]
No tiene cuadro tarifario definido por eso no suma.

**Comment by sebasmoyano** [comment]
Desde la acción ingresar pago
