### ISSUE TITLE
Radatilly - reporte de facturacion

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#115]
seba el TOTAL DE IVA ponelo abajo del TOTAL DE FACTURACION y es en $, sacale el simbolo u$$, acordate que el iva en es pesos.

![image](https://user-images.githubusercontent.com/38771873/49698921-2a265480-fba9-11e8-95d8-ced5835bb8a6.png)

**Comment by sebasmoyano** [comment]
@casma20 ahora el IVA es en pesos. Se agregó la columna código para la factura también.
