### ISSUE TITLE
Radatilly - Modificaciones Reporte General

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#117]
Fecha | Punto venta | Nremito  | N remitoResumen  | N Factura |  Estado |  N° de OC | Razón Social | Destino | Material | Empresa  | Grupo | Camion | Chofer | PesoBruto |  Tara  |  Peso Neto | CatBolsones  |  tn ingresadas  | tn disponibles | tn entregadas | total factura

al final agruegale a lo que ya sumamos

total toneladas entregadas
Total toneladas Ingresadas
Total toneladas disponible

prioridad 1

**Comment by sebasmoyano** [comment]
No entiendo las columnas:
tn ingresadas | tn disponibles | tn entregadas
De dónde saco ese valor?

**Comment by sebasmoyano** [comment]
Agregada columna número remito resumen. Falta definir las columnas del comentario anterior.

**Comment by casma20** [comment]
en la orden de carga estan las toneladas ingresadas y demas

**Comment by sebasmoyano** [comment]
No tiene sentido. Se repetirìa el mismo valor para cada registro. Verificar.

**Comment by casma20** [comment]
pasa que estas conchudas quieren que figure en el reporte general esos datos que nosostros se los damos en el reporte de orden de carga. ellos los tienen tambien en el general. lo que haria yo es solo ponerles los totales finales, y no las columnas, sino todos los totales solicitados al pie del documento

**Comment by sebasmoyano** [comment]
No va a estar bien esos totales. Imaginate que la misma orden de compra se usa en muchos remitos entonces no se puede sumar. Verificar.

**Comment by casma20** [comment]
**Buenos días Marcelo, bueno dale, podes agregar la columna observaciones tambien? asi en ese campo explicamos el motivo de la observacion y podemos verlo en el reporte?**

quieren que aparesca el campo de observacion del remito conformado....una ves observado.

**Comment by sebasmoyano** [comment]
Agregar:
- Tabla resumen órdenes de compra sumando todo para Dolavon.
- Observaciones.

**Comment by sebasmoyano** [comment]
@casma20 se agregó en la página final los totales generales de las órdenes de compra para Dolavon.
También se agregó la columna observaciones al reporte Excel.
