### ISSUE TITLE
Radatilly - Acción observar remito

### ISSUE THREAD

**Issue by sebasmoyano** [sebasmoyano/south-conqueror#122]
Tengamos rechazos de bolsones por ejemplo o existan errores de peso en el remito

En el remito en cuestion, se ingresa mal el valor de la tara, al hacer esto se modifica el peso neto ( porque resulta de la diferencia de peso bruto y tara) entonces el remito sale a YPF con informacion erronea

Ante una situacion similar antes de tener el sistema, se modificaba el reporte que creabamos en excell y listo. Ahora necesitamos que esa corrección la haga el sistema

No vamos a usar la opcion editar porque no queremos modificar la informacion del remito porque el mismo ya fue emitido e impreso y conformado por YPF , lo que queremos es que el peso correcto se ajuste en una linea continua. Cuando hablamos del tema de obsevacion esa era la idea, pero ahora vemos que te modifica la informacion que salio en el remito originalmente impreso y eso no tiene que pasar

**Comment by casma20** [comment]
Tengamos rechazos de bolsones por ejemplo o existan errores de peso en el remito

En el remito en cuestion, se ingresa mal el valor de la tara, al hacer esto se modifica el peso neto ( porque resulta de la diferencia de peso bruto y tara) entonces el remito sale a YPF con informacion erronea

Ante una situacion similar antes de tener el sistema, se modificaba el reporte que creabamos en excell y listo. Ahora necesitamos que esa corrección la haga el sistema

No vamos a usar la opcion editar porque no queremos modificar la informacion del remito porque el mismo ya fue emitido e impreso y conformado por YPF , lo que queremos es que el peso correcto se ajuste en una linea continua. Cuando hablamos del tema de obsevacion esa era la idea, pero ahora vemos que te modifica la informacion que salio en el remito originalmente impreso y eso no tiene que pasar

**Comment by sebasmoyano** [comment]
@casma20 Modificada acción para observar remito. Los campos modificados se guardan aparte. Todavía no se muestra en los reportes. Verificar si es correcto.

**Comment by sebasmoyano** [comment]
@casma20 Se agregaron los campos de la rectificación a los reportes excel: remitos y general.
