### ISSUE TITLE
Radatilly - Resumen remito calcular número remito

### ISSUE THREAD

**Issue by sebasmoyano** [sebasmoyano/south-conqueror#123]
Calcular número remito a partir de los remitos existentes.

**Comment by casma20** [comment]
acordate de generar lo numeros automaticos para el pusto de venta de la filomena que son distintos a los de dolavon

**Comment by sebasmoyano** [comment]
@casma20 se implementó esto. Se basa en la numeración de **Dolavon**.

**No cambiar el nombre de los puntos de venta.**
