### ISSUE TITLE
Radatilly- Reportes (todos)

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#128]
Me comentan seba que los reportes no salen ordenados por numero de remitos, ni en el excel ni en pdf.
yo revise en pdf el reporrte de remitos y es verdad comienda por el ....540 y despues en el medio esta el 417.
![image](https://user-images.githubusercontent.com/38771873/50062818-f12d4780-0187-11e9-98bf-ab2ce5219ae9.png)

**Comment by sebasmoyano** [comment]
@casma20 listo, ordenado por número remito ascendente para reporte de remitos y general.
