### ISSUE TITLE
Radatilly-Resumen remitos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#129]
Acordate que si organizamos OC más destinos más material...en la impresión cuando agrupes los remotos al final le pones el material que corresponden

**Comment by sebasmoyano** [comment]
@casma20 
- Agregado campo material al resumen de remitos.
- Mejorado ancho de columna `Remitos` en tabla. Se deformaba todo.
- Impresión de material debajo de remitos.
