### ISSUE TITLE
San Fernando - Menu de viajes

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#13]
FALTA EL MENU DE VIEAJES QUE ESTA EN EL SISTEMA NUEVO....TE LO FUMASTE¡?¡?¡?¡?

**Comment by sebasmoyano** [comment]
El nombre es "Envío de Materiales".

**Comment by casma20** [comment]
DALE SEBA NECESITO ESTE MENU FUNCIONANDO

**Comment by sebasmoyano** [comment]
@casma20 necesito acceso a la VPN.

**Comment by sebasmoyano** [comment]
@casma20 Reestablecido menú `Envíos de materiales`.
