### ISSUE TITLE
Radatilly - Remito resumen - Número de remito resumen

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#131]
Si creas muchos remitos resumen y volver al menú de crear remitos en proceso. El número de remito nunca sigue en correlativo con resumen remito. Sino que se queda con el último que tiene en el listado.

Ahora sí haces la operación a la inversa creando muchos remitos en proceso. En resumen remito figura siempre bien el número.

**Comment by casma20** [comment]
aparte seba acordate que no klista todos los remitoes en una oc ejemplo:

 OC 99350 malla 30-70 :
30612-30613-30649-30660

**Comment by sebasmoyano** [comment]
@casma20 arreglado esto.
