### ISSUE TITLE
Radatilly-reporte de OC mal los encabezados urgente

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#133]
asi deberia decir
Toneladas   disponibles | Toneladas   ingresadas | Toneladas   entregadas |  

asi dice ahora:
Toneladas   ingresadas | Toneladas entregadas | Toneladas disponibles |  

tenes que cambiar el titulo seba esta invertido.

**Comment by sebasmoyano** [comment]
@casma20 arreglado.
