### ISSUE TITLE
radatilly - reporte oc

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#134]
![image](https://user-images.githubusercontent.com/38771873/50254752-17442900-03ce-11e9-8281-e9af0af7a029.png)

![image](https://user-images.githubusercontent.com/38771873/50254851-6ab67700-03ce-11e9-8b5e-5d3056f20f12.png)

Cuando largas el reporte de orden de compra podes ver que, EN LOS anulados el remito tiene las cantidades. No debe ser así, tienen que estar en cero (0) ya que eso no será facturado.

**Comment by sebasmoyano** [comment]
Solo en el reporte? O en el remito también? Cantidad de qué?

**Comment by sebasmoyano** [comment]
@casma20 cerrando por ahora.
