### ISSUE TITLE
Radatilly-Error En reporte Excel

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#135]
Cuando tiras un repórte de remito en excel,  sus valores rectificados salen con coma y cortados, como si truncara los valores de toneladas y le agrega ceros y coma.
En el pdf salen correcto.

ejemplo: remito filomena 7-006003

![image](https://user-images.githubusercontent.com/38771873/51075323-ad374080-1668-11e9-8db1-8d194e562c29.png)

**Comment by sebasmoyano** [comment]
El sistema funciona correctamente. El problema es que cargaron las rectificaciones en toneladas. Se deben cargar en **kilos**. 
Para este tipo de problemas verificar con otros ejemplos. Por ejemplo el remito `0005-00030529` está correctamente cargado.
