### ISSUE TITLE
Radatilly - Error en Reporte General

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#136]
![image](https://user-images.githubusercontent.com/38771873/51210723-47f68000-18f2-11e9-8a74-176e334b54d0.png)

Seba si te fijas en la imagen existe un resumen remito, 005-0030620 qure tiene asociado varios remitos, pero a la hora de sacar el reporte general, tanto en PDF como EXCEL, el campo numero de REMITO RESUMEN de cada REMITO ASOCIADO, aparece vacio. NO HAY VARIOS REMITOS RESUMENES QUE NO PARECEN EN EL REMITO RESUMEN, esto empezo despues de la actualizacion del sabado parece, ya que la semana pasada la gente lo podia sacar me cometan..

![image](https://user-images.githubusercontent.com/38771873/51210900-b6d3d900-18f2-11e9-841f-1c7481319997.png)

Fijate si me lo podes sacar porque tienen que facturarle a PAE esta semana. porfvor.

**Comment by sebasmoyano** [comment]
Como charlamos los remitos asociados tienen problemas de validación. Habrá que revisar uno por uno y luego forzar una edición en el remito resumen de modo que propague la asociación a los remitos.
