### ISSUE TITLE
Radatilly - Remitos - Verificación de stock solo al crear

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#139]
[errores.docx](https://github.com/sebasmoyano/south-conqueror/files/2770173/errores.docx)

**Comment by sebasmoyano** [comment]
@casma20 arreglado esto. Solo se verifica el stock al momento de crear un **nuevo** remito.

Para marcar como **facturados** los remitos tenés que guardar la factura correspondiente.
