### ISSUE TITLE
Radatilly - Administración de notas de crédito y débito

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#142]
Seba hay que agregar el modulo que ya tenemos de NOTA DE CREDITO y de Debito del camion club y retocarlo un poco. Pero es exacto como ya tenemos, hasta la impresion en pdf de las notas.

**Comment by sebasmoyano** [comment]
@casma20 implementado esto.
Queda pendiente:
- Impresión PDF.
- Afectación de reportes
Abrir nuevos issues una vez que se conozcan los requerimientos.
