### ISSUE TITLE
Mica - Sistema de Tareas

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#148]
si le asigno una tarea a un grupo de personas, solo recibe el e-mail avisando de la tarea, el primero elegido. Los demas no se enteran.
la idea principal seria que todos se enteren y que cuando uno de ese grupo inicie la tarea, los demas vean el progreso hasta la finalizacion.

**Comment by sebasmoyano** [comment]
Fijate que no esté en el spam.

**Comment by sebasmoyano** [comment]
Puede haber un delay de hasta 5 minutos para recibir el correo.

**Comment by casma20** [comment]
Si, llegan al spam, ya lo arregle.
igual esta mal algo seba porque un operador que no este asegnado a una tarea, NO PUEDE ver las tareas de los demas.
solo las que fue nombrado.
solo los administradores pueden ver todo.

**Comment by sebasmoyano** [comment]
Si está entre los asignados la verá.

**Comment by casma20** [comment]
Claro. Así debe ser. Pero este caso el flaco no estaba asignado y ve todo

**Comment by casma20** [comment]
También cuando cerrad la tarea debería salir un campo comentario para saber porque se cerró. Sino tengo que hacer un comentario antes y después cerrarla sino no queda asentado porque pijotas se cerró.

**Comment by sebasmoyano** [comment]
Dame el nombre del usario.

**Comment by casma20** [comment]
Ulises munioz

**Comment by sebasmoyano** [comment]
Creadas tareas separadas.
