### ISSUE TITLE
Radatilly - Reporte genel

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#153]
Tambien es necesario que en el reporte general salgan todos los puntos de ventas , por el momento si emitimos un reporte general sale solo el punto de venta 0005 y el punto 0007 que es de Filomena no figura

**Comment by sebasmoyano** [comment]
Esto no es verdad. Acabo de chequear y salen los remitos para todos los puntos de venta. De hecho funciona bien el filtro de punto de venta.

Por favor verificar antes de abrir un issue.

**Comment by sebasmoyano** [comment]
@casma20 ver comentario.
