### ISSUE TITLE
Mica - Gestión Tareas - Error al iniciar tarea

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#154]
![image](https://user-images.githubusercontent.com/38771873/52820359-8c5c7380-308a-11e9-929b-392e20962f35.png)

no puedo poner en marcha estas tareas que me asignaron

**Comment by sebasmoyano** [comment]
@casma20 arreglado. Acordate que solo vos podés mover tareas cuando no sos el responsable.
