### ISSUE TITLE
Radatilly- OC sin stock dejan crear remitos y exceden material

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#155]
### **6 feb. 2019 a las 11:14, Paula Sanchez Cordi (<adm.transporteradatilly@gmail.com>) escribió:**

    Buen dia Sebastian , por favor avisanos si hay  problema para modificar de lugar en el sistema el rto. 31152 , aun figura  en la OC 51377 # 30-70 y no en la OC52453 # 30-50.-
    Si los saldo se corrigieron, gracias.
    Otra consulta , ayer dejo el sistema ingresar un remito el cual excedia las toneladas cargadas de la OC 51377 # 30-70 y quedo en negativo , por favor fijate porque esto no deberia ocurrir . 
    Aguardamos comentarios.
    Muchas gracias
    Saludos
    Paula

![image](https://user-images.githubusercontent.com/38771873/52949135-2ad22880-335a-11e9-89e1-c0896d476be8.png)

 **### 7 feb. 2019 a las 12:22,**
dejo el sistema ingresar un remito el cual excedia las toneladas cargadas de la OC 51377  material 

30-70 y quedo en negativo , por favor fijate porque esto no deberia ocurrir . 
Aguardamos comentarios.

![image](https://user-images.githubusercontent.com/38771873/52948968-c57e3780-3359-11e9-911e-3bbaa512b588.png)

### **12 feb. 2019 a las 13:00, Paula Sanchez Cordi**
Buen dia Marcelo !!! pudieron ver estos temas , en el caso de PAE Cerro Dragon aun tenemos esas diferencias ya que los remitos que excedieron las OC que te pegue  deben ir la nueva OC de los cliente , en ambos casos seria la 4100106995.
Por favor fijate si podes mover los remitos en cuestion .
En el caso de Vista aun figura en el sistema el rto. 31152   en la OC 51377 # 30-70 y no en la OC52453 # 30-50.- como corresponde , si los saldos estan bien.
Por favor avisanos si tiene solucion.

### **El mar., 12 feb. 2019 a las 13:00, Paula Sanchez Cordi (<adm.transporteradatilly@gmail.com>) escribió:**

    Buen dia Sebastian y marcelo !!! pudieron ver estos temas , en el caso de PAE Cerro Dragon aun tenemos esas diferencias ya que los remitos que excedieron las OC que te pegue  deben ir la nueva OC de los cliente , en ambos casos seria la 4100106995.
    Por favor fijate si podes mover los remitos en cuestion .
    En el caso de Vista aun figura en el sistema el rto. 31152   en la OC 51377 # 30-70 y no en la OC52453 # 30-50.- como corresponde , si los saldos estan bien.
    Por favor avisanos si tiene solucion.
    Gracias
    Saludos
    Paula

**Comment by casma20** [comment]
remitos que se crearon sin stock
FECHA | NUMERO REMITO
6-feb.-19 | 0005-00031230
15-feb.-19 | 0005-00031668
15-feb.-19 | 0005-00031669
5-feb.-19 | 0005-00031211

**Comment by sebasmoyano** [comment]
@casma20 cuando se crea un remito se valida bien. 
![validar](https://user-images.githubusercontent.com/5084534/52981408-5be44480-33be-11e9-9033-631217590d3f.png)

Parece que tiene saldo negativo porque han estado metiendo mano. Ahora:
- No se puede modificar la orden de compra de un remito ya creado.
- El saldo disponible de la orden de compra siempre tiene que ser mayor a 0.
