### ISSUE TITLE
Mica - Reporte facturación múltiple

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#156]
Seba necesito que las facturas realizadas aparescan cuando tiro reporte de iva o movimientos, en ningun lado las encuentro y el contador no puede ver el iva.
POrque no aparecen?

**Comment by sebasmoyano** [comment]
Porque no se pidió como requerimiento. Lo podemos agregar. Que sea una página aparte? Luego que se sume en los totales?

**Comment by casma20** [comment]
si porfavor, asi salen ordenados. si lo podes hacer para hoy mejor asi queda peolaaa vago

**Comment by sebasmoyano** [comment]
@casma20 implementado reporte de facturación múltiple.
