### ISSUE TITLE
Radatilly - Creación y asignación de remitos a una factura

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#158]
Seba, evidentemente algo esta pasando porque me quede anoche cargando 45 remitos de la factura 005-0000206, porque NINGUNA figuraba como facturada, me tome el trabajo una por una de ver si estaban los datos cambiados, tenian diferentes ordenes, datos de chofer o algo y encontre solo 5 que tenian diferencias, las demas estaban correctamente asociadas.
Tambien le cambie la hora de creacion a la factura a ver si asociaba a los remitos...nada, revise la OC para ver si habia algun error,la edite, la guarde.
asi que tuve que ingresar uno por uno el num de factura y cambiarle el estado a cada remito

si cada ves que alguien hace una factura y me llenan la casilla de mensajes o mails porque no encuentran los remitos asociados a la factura me van a romper la pija....entonces no me sirve. quiere decir que esta funcionando mal. Porque SGA que hace lo mismo con el tema de las facturas no me llaman?? y hace lo mismo.

revisar

**Comment by sebasmoyano** [comment]
Si no cambia el estado es porque tiene errores de validación. Es una cuestión de capacitación de usuarios. Les tenés que enseñar a cargar correctamente.

**Comment by sebasmoyano** [comment]
Sga tiene formularios más simples y usuarios más capacitados al parecer.

**Comment by sebasmoyano** [comment]
Lo que si voy a cambiar es que si una tiene errores continúe igual con las otras, o sea que no pare el proceso de asignación del estado.

**Comment by sebasmoyano** [comment]
Se realizaron las siguientes mejoras:
1. Si uno de los remitos tiene errores de validación en el proceso de asignación de la factura el proceso no se parará, continuará asignando los otros registros.
2. Agregada herramienta para facilitar el manejo de remitos con problemas. Existe un nuevo campo llamado: `Remitos no asignados` que solo vos verás. Ahí listará los remitos con problemas. Este campo se re-calcula cada vez que guardás la factura.
