### ISSUE TITLE
Mica - impresion de factura ticket

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#159]
Anoche tuve que sacar a las apuradas, notas de credito..facturas multiples...y facturas comunes en el sistema porque EL SISTEMA DE TAREAS NO ME AVISAAAA PORQUE NO ME LLEGAN LOS MAILS.

que paso, todas las notas de credito y las facturaciones multiples......salieron de toque...como pan caliente... creaba imprimia creaba una imprimia.... nunca se trabo ni el sistema ni la impresora.

ahora cuando fui a imprimir egresos que teniana atrasados y a generar nuevos ingresos, es un cancer imprimis 2 camiones y el tercero se traba, hay que refrescar toda la pagina volverte a loguear volver a imprimir, se vuelve a trabar un cancer.

evidentemente esa pantalla tiene un problema habria que cambiarla o ver que carajo pasa. si hubiera problemas con internet o algo generalizado no saldria nada.

**Comment by sebasmoyano** [comment]
@casma20 no gritar al escribir por favor.

**Comment by sebasmoyano** [comment]
Estuve probando y no se me traba. Tendrías que mandarme screenshots de lo que pasa en la consola de chrome (Ctrl + Shift + J), tabs `Console` and `Network`.

Por favor reportar los issues con detalles más técnicos, parecés usuario operador jaja.

Cerrando hasta que tenga más feedback técnico. Lo podés re-abrir si persiste.

**Comment by sebasmoyano** [comment]
@casma20 no puedo reproducir el issue como dijiste. Vas a tener que mandarme un video.
