### ISSUE TITLE
Mica - Sistema de tareas

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#160]
NOOOO ME LLEGAN LOS MAILS, anoche me llamaron a las 12 de la noche para que generara facturas, notas de credito y demas mierdas en el sistema porque hoy se vence ganancias y necesitaban los comprobantes.

solo llegan los mails de cierre de tarea

**Comment by sebasmoyano** [comment]
@casma20 arreglado. Al crear una nueva tarea notificará al Responsable y a los asignados.
