### ISSUE TITLE
Mica - Herramienta para verificar facturas

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#161]
existe casos que salta la numeracion ya sea de las facturas A o B y quedan huecos sin completar, necesito que crees un formulario de carga **solo para mi** para rellenar esos campos con los datos necesarios para que quede todo correcto y ordenado en el sistema, pero antes PRESUPUESTALO.... sino me arrancas la cabeza. acordate que no me pagaron todavia.
quiero que el sistema queda cargado con los datos y si faltan facturas fisicas, nos mi problema entendes?, si viene alguna inspeccion de la afip el sistema esta completo.

**Comment by sebasmoyano** [comment]
No se entiende lo que necesitás. Me tendrías que llamar.

**Comment by sebasmoyano** [comment]
@casma20 Ahora puedes crear facturas desde la sección `Facturas emitidas.`
