### ISSUE TITLE
Mica - Nota de débito

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#162]
seba cuando se hace una nota de debito, lo que tenes que buscar son las NOTAS DE CREDITO HECHAS y cargar sus datos, no la estadia. las notas de debitos anulan notas de credito. En el caso de seleccionar una Nota de Crédito Electrónica sólo podrá anular. Para anular una Nota de Crédito Electrónica debe seleccionar "Generar Nota de Débito de Anulación"
Esta mal, cambiamelo que necesito generar 2 notas de debito porfavor.

tambien fijate en radatilly si esta asi y cambialo.

![image](https://user-images.githubusercontent.com/38771873/53653457-192a3400-3c2a-11e9-9d66-fc6e3cc1453e.png)

**Comment by sebasmoyano** [comment]
Buen googleo.

**Comment by sebasmoyano** [comment]
@casma20 se implementó esto. Tener en cuenta:
- Se unificó la sección de `Notas fiscales` en una. Se agregaron filtros.
- Se agregó el campo `Ajuste de` que signifca si es por una factura o por una nota. Si es por nota se listarán todas las notas. 
- Se actualizaron reportes.
- Se chequeó impresión. Avisame si la nota seleccionada debe salir en algún lado de la impresión.
