### ISSUE TITLE
RadaTilly - Remitos y orden de compra optitativa

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#164]
pan american les pide a radatilly que envien material SIN ORDEN DE COMPRA, no les asigna ni el numero ni el tope de toneladas a enviar. entonces ellos crean  una orden ficticia que la usan para cargar el material a enviar. inventan un numero y un tope de toneladas.

esto genera 2 problemas:

1 cuando les llega la OC real con su numero y su tope de toneladas, la cargan y migran todos los remitos a esa orden.

2 muchas veces la OC el tope de toneladas es MENOR  al enviado, entonces que hacen "GUARDAN" REMITOS para una proxima OC, asi la pueden facturar.

**Comment by sebasmoyano** [comment]
Lo correcto es no crear registros inadecuados por lo que no sería posible crear órdenes de compra ficticias.
Como solución propongo este workflow para el remito:
- Iniciado: carga rápida con datos básicos del remito.
- Pendiente: Se cargan otros datos menos la orden de compra.
- Procesado: Nuevo estado. Para poner un remito como procesado se debe setear la orden de compra real. Por lo que en este momento se crea la orden de compra. 
- Facturado/anulado/observado: para estado final del remito.

Con esta solución se iría sacando lo que está en la columna `En proceso`, que por lo que veo se acumulan registros sin sentido.

**Comment by casma20** [comment]
mmmmmmm despues te llamo

**Comment by sebasmoyano** [comment]
Cerrado por inactividad

**Comment by casma20** [comment]
esto hay que desarrollarlo pero antes hablemos

**Comment by casma20** [comment]
cuando se este cargando el formulario de remitos y se llegue a la parte de ingresar el numero de OC, el sistema tendra una pregunta con un SI O NO, si uds cuentan con el numero de OC real o no, esto es para saber si cuentan con la oc orginal o realmente no la tienen. La idea es diferenciar los remitos que cuentan con OC reales y el proceso sigue en la forma que lo venimos haciendo.
    Cuando la respuesta es NO, el remito se carga como lo venimos haciendo, pero en el listado de REMITOS se genera una columna nueva con un estado nuevo que dice, SIN ORDEN. ¿ que nos permite eso? internamente el sistema guarda el remito en un estado hasta que uds creen la OC real con los valores reales y entonces despues se va a poder asignar cada remito SIN OC a una OC, de la misma forma que a una FACTURA se le asignan REMITOS.
    Con esto logramos que NO EXISTAN OC FICTICIAS, y uds saben que remitos cuentan con oc y cuales no. Tambien les permite asignar un REMITO SIN ORDEN a  cualquier OC creada y en el caso que la sumatoria total de TN no corresponda con los remitos y queden algunos afuera para la proxima facturacion se pueden asignar tambien.

**Comment by sebasmoyano** [comment]
@casma20 se implementó esto: 
- Ahora se pregunta si se tiene la orden de compra. Si la tiene se obliga a ingresarla. 
- Se puede filtrar por una columna nueva llama `Tiene orden de compra`.
- Agregada acción `Asignar orden de compra` en el listado de remitos. Para ejecutarla se seleccionan los remitos que se deseen y se les asigna la orden de compra. Siguen aplicando los mismos filtros para el campo parámetro.

Sacaría algunas columnas del listado, fijate cuáles no se usan.

**Comment by casma20** [comment]
seba ayer me mostraba un combo para elejir las ordenes de compra a asignar, hoy no me sale ninguna.
![image](https://user-images.githubusercontent.com/38771873/55292997-76e7a280-53c7-11e9-9a18-735e1645d99e.png)

**Comment by sebasmoyano** [comment]
@casma20 arreglado.
