### ISSUE TITLE
Mica-Impresion Nota de Debito

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#165]
no se puede imprimir seba, da error

![image](https://user-images.githubusercontent.com/38771873/53963178-86771280-40cb-11e9-9c12-6e1c2d177d3c.png)

**Comment by sebasmoyano** [comment]
Probá imprimir por una factura.

**Comment by sebasmoyano** [comment]
@casma20 Probá imprimir por una factura.

**Comment by casma20** [comment]
NO, no se puede tira un error

**Comment by sebasmoyano** [comment]
No entiendo, no podés imprimir nada?

**Comment by sebasmoyano** [comment]
@casma20 cerrado por inactividad.
