### ISSUE TITLE
Mica- Sistema de Tareas- Error al pasar a tareas en proceso

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#166]
![image](https://user-images.githubusercontent.com/38771873/54752762-f8685500-4bbd-11e9-945c-4e653b0e294f.png)

crearon la tarea 59 y no se puede inciar. a mi tampoco me deja

**Comment by sebasmoyano** [comment]
@casma20 qué usuario es?

**Comment by casma20** [comment]
Tiene que haber sido algun error temporaneo, no se volvio a repetir.

**Comment by sebasmoyano** [comment]
Ok
