### ISSUE TITLE
Radatilly - Formulario de facturación

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#167]
se necesita agregar a una misma factura, distintos materiales a facturar.

por ejemplo, misma razon social------mismo destino-----pero distinto material, entonces en una misma factura creada, quedaria la sumatoria total de los 2 materiales a facturar.

llamame y lo vemos....

**Comment by sebasmoyano** [comment]
@casma20 es un cambio importante porque todo está atado al remito.

**Comment by casma20** [comment]
llamame seba asi me explicas un poco que pasa

**Comment by casma20** [comment]
acordate crear el combo de la misma forma que la facturacion multiple

**Comment by sebasmoyano** [comment]
@casma20 se realizaron las siguientes tareas:
- Cambiada estructura para que una factura pueda tener N destinos y N materiales para una razón social en particular.
- Se migraron los datos existentes a la nueva estructura de datos.
- Se arreglaron a mano unas 10 facturas que estaban mal cargadas. Solo una no la pude arreglar porque estaban mal cargados los datos. Vas a tener que editarla y arreglarla. Estos son los datos:
![187](https://user-images.githubusercontent.com/5084534/55367774-09ba3700-54c5-11e9-8c0f-ba214331d2b3.png)

No sé cómo sería el tema de los reportes. Abrite un nuevo issue para eso.

**Comment by sebasmoyano** [comment]
No sé cómo sería el tema de los reportes. Abrite un nuevo issue para eso.

**Comment by sebasmoyano** [comment]
@casma20 sacadas columnas de reporte.
