### ISSUE TITLE
San Fernando - Órdenes - Migrar datos sistema viejo

### ISSUE THREAD

**Issue by sebasmoyano** [sebasmoyano/south-conqueror#17]
Migrar:
- Empresas
- Choferes
- Camiones
Desde la base de datos MySQL según backup: https://drive.google.com/drive/folders/1-GHpDyByBJehQcOP2ECriPIgbDuzKID2

**Comment by sebasmoyano** [comment]
@casma20 al igual que en sga había mucha información mal cargada en el sistema anterior.
Se migraron:
- Localidades
- Choferes: 4000 aprox.
- Empresas: 2000 aprox.
- Camiones: 2000 aprox.

También se puso botones para crear empresas/choferes/camiones al momento de la carga de una orden de carga.

[migracion_sistema_ordenes.tar.gz](https://github.com/sebasmoyano/south-conqueror/files/1977033/migracion_sistema_ordenes.tar.gz)

**Comment by casma20** [comment]
seba te olvidaste migrar el numero de proveedor, no figura en ningun lado, fijate que el numero de proveedor ESTA ASOCIADO A CERAMICA SAN LORENZO, si el trasnsportista no lo tiene no puede cargar arcilla. El sistema viejo tenia el campo de carga en transportista y lo imprime en la ORDEN DE CARGA. y EN LA GUIA. 

ahora no se imrpime en ningun lado.

**Comment by sebasmoyano** [comment]
@casma20 migrado número proveedor e impreso en la orden de carga.

Cerrando...
