### ISSUE TITLE
Copiatinta

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#174]
https://www.contabilium.com/api-desarrolladores/

https://app.contabilium.com/login.aspx

hechale una mirada

logueate
usuario:      marcelo.casanova@southconqueror.com.ar
pass:           Lucia2218

**Comment by sebasmoyano** [comment]
Se ve sencillo. Podés ofrecer ciertas funcionalidades a tus clientes y las podemos implementar de forma parecida.
