### ISSUE TITLE
Radatilly-asignacion de Oc  en remito no resta stock

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#176]
los siguientes remitos que están en la OC 4700198027 a la orden que van a ser ingresados en Pae OC 4700202968

MALLA 2040     remitos: 32911 32920 32949  32968  32985

los cambie en forma de asignacion pero si entras a la oc no estan descontados.

**Comment by sebasmoyano** [comment]
@casma20 fijate ahora. La acción `Asignar orden de compra` estará disponible solo si el remito está `PENDIENTE`.
