### ISSUE TITLE
La rotonda- No puede imprimir en fiscal

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#178]
![image](https://user-images.githubusercontent.com/38771873/56895012-08494380-6a5e-11e9-9351-59349c67b757.png)

seba le sale este error al imprimir una factura.

**Comment by casma20** [comment]
![image](https://user-images.githubusercontent.com/38771873/56895059-362e8800-6a5e-11e9-8c21-735d9d0f1947.png)
 el gestor de impresion dice esto

**Comment by sebasmoyano** [comment]
Arreglado
