### ISSUE TITLE
radatilly- impresion de remitos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#179]
![image](https://user-images.githubusercontent.com/38771873/56902218-291a9480-6a70-11e9-97a0-d564b2d18a3d.png)
no deja imprimir remitos

fijate seba si el quilombo es por estar en la version gratis cambialo

**Comment by sebasmoyano** [comment]
Me funciona bien che. Limpiá caché, logueate de nuevo, etc.
