### ISSUE TITLE
Radatilly - Facturacion

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#181]
Seguimos con el problema de asignar numeros y cambiar el estado a los remitos.

**Comment by sebasmoyano** [comment]
Estimado analista en sistemas, no se entiende nada lo que quiere decir. Cuando reporte un issue por favor:
- Colocar claro los pasos para reproducirlo. 
- Especificar usuario utilizdo.
- Incluir screeshots y videos.

**Comment by sebasmoyano** [comment]
@casma20 cerrado por inactividad
