### ISSUE TITLE
Mica - Camión Club - Entorno de Facturación de Camión Club

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#186]
Seba, sacame porfavor el popup para facturar en el sistema de camion club, cambialo por algo parecido a las nc o a la facturacion multiple andan excelentes y nunca se traba la impresion. han ingresado nuevos usuarios al sistema para usar el sistema y son un desastre...sumado a que envian a imprimir y se les traba, se vuelve una tarea desgastante porque despues hay que hacer nc, sacar camiones que no estan en playa....un desastre.

dale prioridad.

**Comment by sebasmoyano** [comment]
@casma20 Migrado vista de tarjetas a vista tipo tabla. Las transiciones las tenés que hacer con las diferentes acciones. Solo está habilitado para el grupo `Administrador` para que lo pruebes. Si funciona bien se lo activamos a los operadores.

**Comment by sebasmoyano** [comment]
@casma20 ahora se puede imprimir sin que el usuario ingrese nada. La acción se llama `Imprimir factura` y está en celeste. Por favor probalo con los diferentes usuarios, por las dudas no le he deshabilitado la acción `Emitir factura.`
