### ISSUE TITLE
Radatilly - Remitos - Nuevo campo aviso de entrega

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#187]
Seba en el formulario de remito necesito que agregues un campo mas que se llame AE (aviso de Entrega) o si entra ponele aviso de entrega, NO DEBE SER OBLIGATORIO, puede ser tanto numeros como letras.
debe ser filtrado como una columna mas en el formulario de remitos.

el numero debe aparecer en el reporte de remitos y en el reporte general como una columna mas.
es un numero de contro que cargar los operarios de comodoro por algo que no entendi... de panamerica...

**Comment by sebasmoyano** [comment]
@casma20  se realizaron las siguientes tareas:
- Agregado nuevo campo llamado `Aviso entrega`, texto no obligatorio. 
- Agregada columna en listado de remitos.
- Agregada columna en reporte de remitos (PDF y Excel).
- Agregada columna en reporte general (PDF y Excel).
