### ISSUE TITLE
Radatilly - Reporte General - Eliminar hora de la fecha

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#189]
Seba fiajte si podes sacarle al campo fecha del reporte general, la hora. fijate que dice correctamente el dia, mes y año pero sale tambien la hora. fijate si lo podes eliminar, porque las operadoras de comodoro lo van a filtrar por excel....
![image](https://user-images.githubusercontent.com/38771873/57941604-c7e32580-78a5-11e9-9e05-ad32b6975e0d.png)

**Comment by sebasmoyano** [comment]
@casma20 se cambió esto.
