### ISSUE TITLE
Radatilly-Asignacion de Remitos a Facturas

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#191]
seba mira este ejemplo:

![image](https://user-images.githubusercontent.com/38771873/58487275-af90c780-813d-11e9-84e8-28ea99455d09.png)

de todos estos remitos, solo existen errores de validacion en estos 2 remitos 0005-00031295
0005-00031259, ahora NADIE LOS MODIFICO, nadie toco el remito, lo comprobe con la gente de comodoro y de dolavon, osea el sistema solo esta tomando como que estan mal cargados.

te deje los remitos en estado pendiente para que le agregues el campo de numero de factura y veas el error

**Comment by sebasmoyano** [comment]
Nos quieren echar la culpa y por ejemplo el remito **0005-00031295** se ha borrado la empresa transportista asociada.

![transporte](https://user-images.githubusercontent.com/5084534/58598583-5024db80-8253-11e9-9ebd-5c777776d69b.png)

**Si se borra un registro se rompen todos los registros asociados!**

**Comment by sebasmoyano** [comment]
Lo mismo para el remito **00031259**.

![camion](https://user-images.githubusercontent.com/5084534/58598653-a85bdd80-8253-11e9-9b40-aaf6f9d445b7.png)

**Comment by sebasmoyano** [comment]
@casma20 se realizó lo siguiente:
- Ahora no se permite crear o editar la factura si los remitos seleccionados tienen problemas.
- Arreglado campo remitos no asignados.
- Agregada auditoría más severa: 60 días para atrás. Para escrachar a quien borra los registros.
