### ISSUE TITLE
Sistema de Corralones- software guia

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#194]
http://www.libertya.org/

usuario: casmalop
pass: 2UjEjQMS6v263g2

Seba te envio un enlace para que instales el soft de gestion integral que estan usado de guia para migrar sus aplicaciones en algunas corralones, tenes la descarga para windows y para linux o multiplataaforma que dicen ellos.

en pricipio quiero que veas y analises un soft que es gratis...que se puede tocar...y que esta disponible para arrancar ya, tiene los modulos de la afip para controladores fiscales y facturacion electronica, entonces tenemos que competir con esto, ver que prestaciones tiene este soft y que ganarian con nosotros.

fijate si tenes tiempo y analizalo.

**Comment by sebasmoyano** [comment]
Cerrando hasta que haya novedades.
