### ISSUE TITLE
Radatilly - Errores en remitos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#195]
seba hicieron facturas y encontraron errores en los remitos, me puse a investigar los 6 remitos con errores y tenian modificado el chofer del camion, pero no fue eliminado, sino que le agregaron un chofer mas al camion, el sistema lo toma con un error.
la fecha de los remitos creados es anterior a la modificcion

![error_camion](https://user-images.githubusercontent.com/38771873/59454045-9f3c4600-8de7-11e9-997c-1958ed09d4c5.jpg)

**Comment by sebasmoyano** [comment]
Si ha modificado los choferes de ese camión, por lo que veo sacó el que estaba y puso uno nuevo entonces la relación el chofer seleccionado quedará rota. Es el comportamiento esperado y es correcto.

**Comment by sebasmoyano** [comment]
@casma20 respecto a los remitos que no se habían pasado a `Facturado`, el issue ha sido arreglado, se demoraba más de 30 segundos en realizar la operación, por eso se cortaba la ejecución.

**Comment by sebasmoyano** [comment]
@casma20 por favor realizar pruebas!!
