### ISSUE TITLE
Radatilly - Se encontraron errores en unos remitos de una factura

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#199]
pasa algo extraño seba y quiero que me lo expliques: 

el dia 13-02-2019 se modifico el grupo a que pertenecia una empresa llamada alvarez.

![image](https://user-images.githubusercontent.com/38771873/60739904-fc846c80-9f39-11e9-880b-1017c0a9498d.png)

sus remitos se crearon el dia 19-06-2019

![image](https://user-images.githubusercontent.com/38771873/60739947-22aa0c80-9f3a-11e9-8ad1-351ecf9bd977.png)

ahora cuando se creo la factura este remito y otro mas 33774 ,33732 dieron error y les faltaba justamente el GRUPO de la empresa. Porque dio error si la fecha de modificacion fue anterior a la creacion del remito?

**Comment by casma20** [comment]
Como podemos preveer estos cambios antes de llegar a una facturacion o algun resumen remitos...para que los remitos lleguen todos validados??? y asi no comerme las puteadas de las viejas chotas que llaman porque pierden timpo en arreglar estos errores.

**Comment by casma20** [comment]
![image](https://user-images.githubusercontent.com/38771873/61172907-e857f500-a561-11e9-973b-75c24545ad1b.png)
seba aca dnuevo hubo una modificacion y fue anterior a la creacion del remito y lo marca como error.
y no se puede facturar.

**Comment by casma20** [comment]
AD256ZE
![image](https://user-images.githubusercontent.com/38771873/61172934-44bb1480-a562-11e9-967a-9ae815056a1f.png)
si entras a estos remitos 32215.....32057....31931.....32442 no encuentra al otro chofer que te estoy mostrando y en la parte de logistica

**Comment by sebasmoyano** [comment]
@casma20 no se entiende el problema. Es muy difícil laburar así. Quedaste en llamarme y no lo hiciste.

**Comment by sebasmoyano** [comment]
@casma20 Cerrando por inactividad.
