### ISSUE TITLE
Mica - Control Stock - Implementación

### ISSUE THREAD

**Issue by sebasmoyano** [sebasmoyano/south-conqueror#2]
Desarrollo sistema control stock. Según descripción:

> hay que poner el sistema de camion club y toda su base de datos.
y crear este sistema nuevo que lo que hace es tomar los datos cargados 
manualmente de los stock de compbustibles en los distintos tanques, mas 
los aforadores( que son unas barillas especiales que tienen cada tanque) 
y saca un promedio de litros diarios y despues al final un promedio de 
litros mensualas con distintos porcentajes.

> a esto se le podria sumar datos estadisticos de ventas por 
litro....numero de surtidor que mas vendio....combustible que mas se 
vendio....promedio de comprar en el mes...etc.

Referencia:
[control_stock.xlsx](https://github.com/sebasmoyano/south-conqueror/files/1953362/control_stock.xlsx)

**Comment by sebasmoyano** [comment]
@casma20 Se encuentra implementado el control de stock por tanque y producto. Deberíamos hacer una conferencia para mostrarte cómo funciona.

Creé un issue separado para los cambios del dashboard. https://github.com/sebasmoyano/south-conqueror/issues/23

**Comment by sebasmoyano** [comment]
@casma20 arreglado permisos. Deberías ver el menú ahora.

**Comment by casma20** [comment]
falta el dash

**Comment by sebasmoyano** [comment]
@casma20 hay otro issue para el dashboard #23.
