### ISSUE TITLE
San Fernando - Restaurant - Resumen de ventas mensuales

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#20]
seba necesito el menu de ventas diarias o algo asi, que te iba mostrando las ventas diares mensuales y lo sacaste del sistema. el contador solo lo necesita ahi en el restaurant para ver cuandto iva paga por dia.
le es mas util mirarlo ahi.

y si podes sacale el nombre donde dice Sanfernando y ponele LOS VASCOS

**Comment by sebasmoyano** [comment]
@casma20 necesito acceso a la VPN.

**Comment by sebasmoyano** [comment]
@casma20 restaurada funcionalidad. Menú se llama `Ventas Mensuales`.
