### ISSUE TITLE
Control de Flotas - Empresa Don Roberto srl

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#200]
cambios a tener en cuenta.

permisos de operador, 

**### menu crear vehiculos**
- al momento de cargar el vehiculo, colocar el boton "agregar" en campo "empresa aseguradora"

cuando se ingrese una fecha de vencimiento de poliza de seguro, debe emitir una alerta con 1 semana de anticipacion. Lo mismo para el pago de patentes, el vencimiento de carnets o documentacion, (eso no lo tenemos en cuenta en el sistema).
o generar un menu de Gastos por vehiculos.

**### menu combustible**

-al momento de crear en el control de combustible  colocar el boton "agregar" en campo "estacion" y "vehiculo"

- El campo "costo por litro" debe ser ingresado por el usuario el valor real del combustible seleccionado, no un promedio calculado como hace ahora.

### **### menu Combustible mensual**
-Es mas util que sea un reporte detallado por cada unidad de vehiculos en ves de un detalle general numerico campos a tener en cuenta:
consumo total en litros, consumo promedio de combustible, total de $ en combustible, Total $mensual de la unidad.
-el cliente quiere un menu reporte de combustible con filtros por unidad o totales detallados.
-cuando se crea el vehiculo si ingresa la cantidad de km de la unidad, cada ves que se cargue combustible necesita ingresar el nuevo km de la unidad para ser utilizado en los reportes.

**Alerta de cambio de aceite segun km**
una ves ingresado un km para tener en cuenta cada cuanto se necesita un service, el sistema tomaria como referencia el km inicial de la unidad mas un km inicial de cambios de aceite, y cada ves que se carga combustible, restaria el km actual menos el km cambio de aceite y emitiria una alerta al acercarse  el valor a 0. ejemplo
km actual del peugeot 308: 65980km
km del proximo cambio aceite: cada 10000km
alerta de proximidad: km cambio de aceite - (km inicial - km actual combustible) = a 100km

**### Control de Stock de Repuestos** 
Se necesita un menu de control de stock de repuestos y un reporte detallado, para el control de cada reparacion de cada unidad,
campos a tener en cuenta...
codigo general, fecha de compra, detalle del producto, precio con iva, stock del producto, area de almacenamiento, unidad que se utilizo el repuesto. _diferenciar por color el stock casi cero del repuesto._

**Comment by sebasmoyano** [comment]
@casma20 cerrado por inactividad.
