### ISSUE TITLE
Sistema de Remitos - Empresa Don Roberto srl

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#201]
se debe generar un sistema para la carga de remitos de viajes de pescados.
debe controlar ciertos campos que se detalla:

Fecha | Punto de Venta | Número de remito  |  Estado  | N de Factura  |  Razón social | Cuit  |  Destino  | producto |  Empresa transporte | Camión |  Chofer  | Peso bruto | tara  |   peso neto  |  cantidad de cajones  | Precio por viaje |   Observaciones
 
en cada remito el sistema debe dejar guardar una imagen escaneada de documentacion.

Reportes
Cantidad de viajes detalldos
Calculo de comision por Unidad

**Comment by sebasmoyano** [comment]
@casma20 cerrado por inactividad.
