### ISSUE TITLE
Sistema aleatorio de Turnos de Viajes - Empresa Don Roberto srl

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#202]
El sistema debe organizar en forma aleatoria los viajes a distintos destinos de los camiones y permitir tener el mismo numero de viajes cada camion. asi todos los choferes de los camiones al final del mes cobrarian casi lo mismo al tener la misma cantidad de viajes.

**Comment by sebasmoyano** [comment]
@casma20 cerrado por inactividad.
