### ISSUE TITLE
Constantino - Mejoras y errores encontrados.

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#205]
formulario de Ventas

1. Campo Punto de Venta, es necesario Crearlo para organizar las ventas.
2. cuando elijo una venta como consumidor final para crearlo me da error
![image](https://user-images.githubusercontent.com/38771873/63061915-495e4a00-becd-11e9-8de2-9f6456fbcd52.png

formulario de Carga de Producto faltaria:

1. Unidad de medida para la afip
              
![image](https://user-images.githubusercontent.com/38771873/63061182-b0c6ca80-beca-11e9-884e-e47532dc97e5.png)
![image](https://user-images.githubusercontent.com/38771873/63061209-bc19f600-beca-11e9-9c49-0bba793d850d.png)

2. alicuota de IVA
![image](https://user-images.githubusercontent.com/38771873/63061244-d8b62e00-beca-11e9-8890-ca8ed51c51e6.png)

3.posicion impositiva en el IVA
![image](https://user-images.githubusercontent.com/38771873/63061266-ecfa2b00-beca-11e9-9db8-9a339f8a4e42.png)

Habilitar Auditorias en ventas, productos, etc....

-

**Comment by casma20** [comment]
Los informes en excel no funcionan

**Comment by sebasmoyano** [comment]
@casma20 no informamos a la AFIP Alicuota de IVA por renglón de comprobante. Solo por comprobante. Tampoco informamos Unidad de medida a la AFIP, no es obligatorio.

**Comment by sebasmoyano** [comment]
@casma20 arreglado problema con el CUIT. Solo es obligatorio si la empresa es Responsable Inscripto.

**Comment by sebasmoyano** [comment]
No ingresar basura porque la AFIP valida CUITs.

**Comment by sebasmoyano** [comment]
@casma20 se habilitaron los registros de auditoría para las secciones importantes.

**Comment by sebasmoyano** [comment]
@casma20 creado otros issues para desarrollos.
