### ISSUE TITLE
FullTruck - Sistema

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#21]
Se deberia crear Menues de Proveedor, Articulos, Pagos, Reportes, Egresos, Ingresos

**Impresión de comprobantes**
Debe imprimir facturas, notas de crédito, remitos, recibos de cobro y de pago, presupuestos . Todos los comprobantes impresos quedan guardados para consultar en cualquier momento. Al momento de la impresión de cada comprobante se dejan asentados de todos los movimientos de dinero o mercancías de manera automática.

**Control de stock de compras y ventas**
Al ingresar facturas de proveedor se da ingreso automáticamente a los artículos. Al facturar la mercadería, se realizan los egresos automáticamente. debe mantener el historial de ingresos y egresos de cada artículo independientemente, como así también historial de precios de compra y venta.

Debe Permitir el control de múltiples depósitos y mercadería en diferentes situaciones (p. ej. artículos en trasporte, en exposición, en devolución, en reparación, retenidos, extraviados, etc.).

Debe realizar trazabilidad de productos por número de serie o alguna clave especial, y por variaciones (p. ej. piezas y hubicacion).

**Control de caja diaria, cuentas bancarias y otras cuentas**
Debe permitir manejar múltiples cajas, por cada sucursal por si se abre una sucursal en dolavon.... También lleva control de cuentas bancarias asociadas con chequeras, acreditaciones de tarjetas de crédito, cobros con depósito, pagos mediante transferencia, etc.

**Control de cuentas corrientes** de clientes y de proveedores, con límites de crédito globales o por cliente y asiento automático de cobros y pagos al ingresar recibos.

**Control de tarjetas de crédito y débito**
Lleva control automáticamente de cupones de cobro realizados con tarjetas de crédito, débito y otros sistemas de pagó mediante cupón como mutuales, descuento de haberes, etc. Permite controlar cupones sin presentar, presentados pendiente de cobro y cobrados.

Controla la acreditación de las liquidaciones de tarjetas y otros medios de pago en cuentas bancarias.
![image](https://user-images.githubusercontent.com/38771873/39872401-3da5ad0c-543e-11e8-8144-6b429acba8f9.png)

**Control de bancos y cheques**
 llevar control de chequeras, cheques propios y de terceros, cuentas bancarias propias asociadas con una o más chequeras.

Cheques pendiente de pago o cobro, saldo futuro de cuenta corriente bancaria y más.

**Manejo de pedidos**
Permite organizar órdenes de pedido a proveedor y pedidos en transporte y posterior ingreso de mercadería mediante factura de proveedor.

Impresion y manejo de Libro de Iva, y migracion a Excel.

**Comment by sebasmoyano** [comment]
Muy bien el relevamiento :1st_place_medal:

**Comment by sebasmoyano** [comment]
@casma20 cerrando esto hasta que haya una decisión.
