### ISSUE TITLE
Constantino > Mejoras en productos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#210]
Crear y manejar los siguientes campos:
- Imagen
- Código proveedor
- Gestión de unidades de medida.
- Stock
  - Existencia
  - Permite saldo negativo
  - Saldo mínimo
  - Saldo máximo
  - Punto de pedido

**Comment by casma20** [comment]
Tambien otrac osa que vi en varios sistemas de ventas es la caga de precio de listas, hay a veces 5 campos en donde se coloca precios de lista y descuentos, fijate que se maneja tambien segun como se vende, si es al contado o cta corriente etc. te lo dejo para que lo veas

![image](https://user-images.githubusercontent.com/38771873/63605974-6ec21680-c5a5-11e9-9646-335d0295c048.png)

**Comment by casma20** [comment]
cargar imagen del produto, es muy util

**Comment by casma20** [comment]
![image](https://user-images.githubusercontent.com/38771873/63606098-b2b51b80-c5a5-11e9-9962-ad4c5428d32d.png)

**Comment by casma20** [comment]
![image](https://user-images.githubusercontent.com/38771873/63606132-c2346480-c5a5-11e9-92a9-fee2f1370d18.png)

**Comment by sebasmoyano** [comment]
@casma20 
- Se agregaron los campos especificados.
- Las unidades de medida se manejan desde `Parámetros`.
- Respecto al manejo de stock:
  - Un producto se considera como faltante si el stock es 0 o es menor al stock de seguridad.
  - Se puede ajustar masivamente el stock desde el listado de Productos.
