### ISSUE TITLE
Constantino > Logistica y distribucion

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#211]
![image](https://user-images.githubusercontent.com/38771873/63606604-d88ef000-c5a6-11e9-88ff-8ba71cfe1a8d.png)

impresion de remito interno para distribucion de mercaderia

![image](https://user-images.githubusercontent.com/38771873/63606703-0d02ac00-c5a7-11e9-81ae-4e1bf5ba3bd7.png)

movimiento de stock por deposito

![image](https://user-images.githubusercontent.com/38771873/63606785-3b808700-c5a7-11e9-84cd-76c2990ececc.png)

![image](https://user-images.githubusercontent.com/38771873/63606880-7aaed800-c5a7-11e9-9b38-12a9c22230ec.png)

**Comment by sebasmoyano** [comment]
@casma20 cerrando hasta que haya mejores requerimientos.
