### ISSUE TITLE
Constantino > Compra masiva de productos a proveedor

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#214]
Armar dentro del menu compras un fomulario que permita armar un pedido de varios productos por proveedores y codigo de producto.

**Comment by sebasmoyano** [comment]
@casma20 Agregada acción llamada `Carga masiva`:
- Se ve desde el listado.
- Selecciona el proveedor que vende ese producto por defecto. Por ejemplo el producto: `288649 - 1968/2BRONCO`.
- Calcula el total por producto y el total general.
- Genera una compra por proveedor. Es decir que agrupa los productos inherentes a cada proveedor.

**Comment by casma20** [comment]
![image](https://user-images.githubusercontent.com/38771873/64882402-618fc900-d633-11e9-9c73-bc1fb1d4dc03.png)

seba fijate que esta funcinando mal

**Comment by sebasmoyano** [comment]
Decime que productos pusiste y cantidades.

**Comment by sebasmoyano** [comment]
Cerrando por falta de información.
