### ISSUE TITLE
Radatilly > Orden compra

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#216]
seba para arreglar el problema, tuve que ingresar a cada una de estas ordenes de compra, editar y guardarla para que se vea reflejado el descuento en toneladas.
fijate porque no se actualizo automaticamente.

MALLA   16-30 | oc 4700235260 |  
19/08/2019 | reminto 0005-00035195 | 190855 | VAN DER MERWE MARCELO | TRANSPORTES RADA TILLY SA | Comodoro Rivadavia | AA500BB-AA263ZU | PAE | TRT SA | 24 | 53,34 | 16,72 | 36,62
 
MALLA #   100 | oc 4700235102 |  
06/09/2019 | remito 0005-00035366 | 190871 | RUMIPILLAN CARLOS | TRANSPORTES RADA TILLY SA | Comodoro Rivadavia | AA500BC-AD288IN | PAE | TRT SA | 24 | 51,06 | 16,12 | 34,94

**Comment by sebasmoyano** [comment]
Puede que en su momento hayan tenido problemas de validacion por lo que no se descontó en la orden de compra.

**Comment by sebasmoyano** [comment]
@casma20 arreglado. El problema fue que lo editó directamente por el formulario de edición. Por lo que el peso neto del remito no cambió pero si cambió el flag `Tiene orden de compra.`
