### ISSUE TITLE
Radatilly > Remitos > Agregar hora de salida

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#217]
seba, en el formulario de carga de un remito, nosotros le agregamos el campo de hora de carga, que luego sale impreso en el mismo formulario.
Lo que estan necesitando es otro campo mas en el formulario que diga hora de salida y se imprima en el remito, justo de lado de la hora que tenemos ahora.

![image](https://user-images.githubusercontent.com/38771873/65258733-ca66bd80-dad9-11e9-95b4-dfd5b6cb2e52.png)

**Comment by sebasmoyano** [comment]
@casma20 implementado esto. La hora de salida se imprime a la derecha de la hora de carga. Fijate si está bien la posición.
