### ISSUE TITLE
San Fernando > Formulario de carga de IVA ventas y compras

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#220]
[Iva Vtas. San Fernando Julio-Diciembre 2019.xlsx](https://github.com/sebasmoyano/south-conqueror/files/3665714/Iva.Vtas.San.Fernando.Julio-Diciembre.2019.xlsx)
[Iva Cpras. San Fernando Julio-Diciembre 2019.xlsx](https://github.com/sebasmoyano/south-conqueror/files/3665715/Iva.Cpras.San.Fernando.Julio-Diciembre.2019.xlsx)
[Iva Cpras. San Fernando Julio-Diciembre 2019.xlsx](https://github.com/sebasmoyano/south-conqueror/files/3665716/Iva.Cpras.San.Fernando.Julio-Diciembre.2019.xlsx)
[Iva Vtas. San Fernando Julio-Diciembre 2019.xlsx](https://github.com/sebasmoyano/south-conqueror/files/3665717/Iva.Vtas.San.Fernando.Julio-Diciembre.2019.xlsx)

seba hay que crear un formulario dentro del sistema para que puedan calcular los IVA de la misma forma que lo hacen en las planillas, y sacar los reportes correspondientes

**Comment by sebasmoyano** [comment]
@casma20 se implementó esto:
- Libro IVA: formulario carga.
- Libro IVA mensual: totales sumarizados por mes.
