### ISSUE TITLE
Restaurant > Formulario IVA compra y ventas

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#221]
[Iva Compras 2019 - Alastuey1.xlsx](https://github.com/sebasmoyano/south-conqueror/files/3665719/Iva.Compras.2019.-.Alastuey1.xlsx)
[Iva Ventas 2019 - Alastuey.xlsx](https://github.com/sebasmoyano/south-conqueror/files/3665720/Iva.Ventas.2019.-.Alastuey.xlsx)

lo mismo que san fernando.

**Comment by sebasmoyano** [comment]
@casma20 como discutimos, todavía no se va a implementar acá.
