### ISSUE TITLE
San Fernando > Menu IVA

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#223]
seba, saca el libro de iva y el resumen , en un menu aparte, que no quede dentro de Ordenes.

agregale tambien en el furmulario, el boton de crear empresas si no existen en el listado.

**Comment by sebasmoyano** [comment]
@casma20 se puso una nueva sección llamada **Impuestos**. Ahora se pueden crear nuevas empresas desde el formulario.
