### ISSUE TITLE
Mica > Administración de ventas de combustible

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#226]
[federico gallardo.xlsx](https://github.com/sebasmoyano/south-conqueror/files/3801609/federico.gallardo.xlsx)

en el siguiente archivo se cargan las ventas de combustibles, lubricantes, cuentas corrientes , vesprini que es la empresa socia de la estacion, ventas de la tarjeta ypf en ruta, te mande una vacio y el otro con algunos datos

[federico gallardo (Autoguardado).xlsx](https://github.com/sebasmoyano/south-conqueror/files/3801612/federico.gallardo.Autoguardado.xlsx)

habria que hacer lo siguiente:
el usuario accede con su loguin, carga los datos en los distintos campos, el sistema calcula las sumas y valores por campos, genera un reporte que se imprime en pdf y automaticamente una ves guardado debe darle al usuario la opcion de enviar por mail el pdf creado.
esta planilla se envia a 4 emails distinto y uno de ellos es a un controlador de ypf.

**Comment by sebasmoyano** [comment]
@casma20 no se entiende nada la planilla.

Por favor pasar en limpio cómo sería el formulario.

**Comment by sebasmoyano** [comment]
@casma20 cerrando por falta de feedback.

**Comment by casma20** [comment]
![image](https://user-images.githubusercontent.com/38771873/73281155-4d0d3100-41ce-11ea-9669-4a125da681a7.png)
neesito que crees un formulario con los campos del excel,columnas. que se comleten y calculen el recuadro de la derecha. y despues te digo que reporte sacar.
tambien que estos datos del formulario se completen en un archivo pdf para ser enviado por mail. predestinado en el sistema

**Comment by sebasmoyano** [comment]
@casma20 se implementó una parte del issue.

### Características
- Administración de turnos. 
- Administración de movimientos para un turno determinado. Un turno puede tener N movimientos para distintos conceptos.
- Administración de conceptos.
- La opción de menú que engloba se llama **Estación**
- Creado nuevo rol  **Operador estación**.
- Reportes de movimientos por fechas y usuario. Sumariza al final.

### Workflow
- Un operador inicia sesión cargando un nuevo turno. Puede tener solo un turno a la vez.
- Carga movimientos en el detalle del turno. 
- En el turno se sumarizan los movimientos agrupados por concepto. Se calcula el total general también.
- Cuando un operador decide finalizar su turno ejecuta la acción `Finalizar turno`.

Me tenés que confirmar que está todo OK para generar el PDF (requiere integración) para mandarlo por correo. Crearé una nueva tarea para soportar esto.

**Comment by sebasmoyano** [comment]
Creado issue #227.
