### ISSUE TITLE
Radatilly > Manejo de remitos internos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#228]
1 se necesita crear un formulario de remito que se capas de cargar los datos e imprimirlos para administrar cargas y viajes de distintos tipos de destinos. Osea si ves el formulario de remito actual, depende de una oc y de ahí tiene asociado el destino...la localidad....los materiales....las TN.
Este nuevo formulario es libre y se utilizaría para viajes internos a plantas procesadores de material entonces no dependen de nada. No tendría restricciones a la hora de cargar sus datos .
Los campos serían los mismos MENOS OC y bolsones, debe imprimirse con la misma alineacion en el papel. y debe figurar en los reportes generales y reportes remitos internos. 
OJOOOOO el nuemro de remito se ingresaria en forma manual, el sistema debe contemplar que no este en uso el remito y avisarle al usuario.

**Comment by sebasmoyano** [comment]
@casma20 se realizó la implementación de remitos internos.

- Los remitos internos se manejan con un tipo: `Interno`. Los existentes son de tipo `Externo`.
- Los tipos internos no requieren Orden de Compra ni cantidad de bolsones.
- Los tipos internos se muestran celestes en las tarjetas de las vistas.
- Se agregaron más filtros a las vistas de remitos.
- Se agregó la columna tipo a los reportes generales y de remitos. Solo Excel en pdf no queda espacio.

Si utilizan una numeración distinta podés crear un nuevo punto de venta, por ejemplo Dolavon interno y un nuevo talonario.
