### ISSUE TITLE
Radatilly - Gestión de talonarios

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#229]
seba se le ha asignado nuevos numeros de remitos a radatilly por el vencimiento del famoso CAE  en sus formularios de papel, entonces existen varios cientos de remitos correlativos impresos que hay que anularlos, y para no hacerlos a mano:
1) deberia haber una seccion de anular remitos, que debe contar con un numero de remito de inicio y un numero de remito para finalizar , un campo para poner el porque de laanulacion del conjunto de remitos y cambiar el estado de anulado de todos esos numeros, guardarlos en el sistema y obviamente el sistema no podra reeutilizar esos numeros.
2)El correlativo de remitos anulados deben aparecer en los reportes generales y de remitos pdf/ Excel como anulados y en sus campos en cero o vacios.

**Comment by sebasmoyano** [comment]
Se implementó la gestión de talonarios ubicado en la sección de `Gestión`.

El manejo de talonarios es por punto de venta.

### Workflow
Un talonario puede tener los siguientes estados:
- **Activo**: los remitos tomarán la numeración desde este talonario. Se puede tener un solo talonario activo a la vez. Para pasar un talonario a `Activo` se debe ejecutar la acción: `Marcar como activo`. Pondrá los demás talonarios existentes como `Inactivo`.
- **Inactivo**: significa que ya fue usada toda su numeración o que se deja de usar por X motivo.Para pasar un talonario a `Inactivo` se debe ejecutar la acción: `Marcar como inactivo`.
- **Anulado**: significa que un rango determinado está anulado por ejemplo por vencimiento de CAE. Para pasar un talonario a `Anulado` se debe ejecutar la acción: `Anular formulario` especificando observaciones. Dicha acción desencadenará la anulación de los remitos en el rango. Utiliza las observaciones de la acción.

 ### Numeración de remitos
La numeración de remitos y resumen remitos es tomada del talonario activo actual. El talonario activo tiene un campo llamado `Número actual` que es el último remito creado de mayor numeración. Cualquier inconveniente podés modificar ese campo.
Se valida que haya un talonario activo para un determinado punto de venta cada vez que se crea un remito. También se valida que el talonario posea slots de numeración libres.

**Comment by sebasmoyano** [comment]
@casma20 Solo Administradores y Administrador Dolavon pueden ver la sección

**Comment by sebasmoyano** [comment]
@casma20 creé 2 talonarios (Dolavon y Filomena) para que puedan trabajar y no te molesten mientras tomás quinta vacaciones de 2020.
