### ISSUE TITLE
MIca- Camion Club Espacios en blanco en facturacion

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#230]
hay espacios en blanco en la facturacion.

**Comment by casma20** [comment]
[gestor-impresiones.log](https://github.com/sebasmoyano/south-conqueror/files/4996712/gestor-impresiones.log)

[gestor-impresiones2.log](https://github.com/sebasmoyano/south-conqueror/files/4996717/gestor-impresiones2.log)
[gestor-impresiones3.log](https://github.com/sebasmoyano/south-conqueror/files/4996722/gestor-impresiones3.log)

**Comment by casma20** [comment]
mmm

**Comment by sebasmoyano** [comment]
@casma20 cerrando por ahora.
