### ISSUE TITLE
SGA-Generar en reportes generales el reporte de movimientos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#239]
En el menu reporte de movimientos se selecciona una x cantidad de remitos y despues como accion se genera un excel con los campos generados.
![image](https://user-images.githubusercontent.com/38771873/108729295-21f82c80-7509-11eb-9d7f-87fb6596c4dc.png)

![image](https://user-images.githubusercontent.com/38771873/108729358-31777580-7509-11eb-8236-c4a50b395760.png)

Tarea:
Habria que generar en REPORTES GENERALES un nuevo reporte que diga, REPORTES DE MOVIMIENTOS, y al final en ves de generar un pdf, que genere un EXCEL con los mismos campos que tiene como accion en el reporte de movimientos.

**Comment by sebasmoyano** [comment]
@casma20 implementado esto.
