### ISSUE TITLE
Mica-CamionClub-No se puede dar de alta un camion ni sacar con el cursor los que estan en playa.

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#247]
![image](https://github.com/sebasmoyano/south-conqueror/assets/38771873/9dc2131c-93e2-4ee6-9490-44517ea5930c)

cuando intentas crear un camion, no te deja continuar una ves cargado la marca del camion

**Comment by sebasmoyano** [comment]
Arreglado.
