### ISSUE TITLE
Radatilly-Ordenes de Compra- Menu se traba y no ejecuta nada

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#249]
![image](https://github.com/sebasmoyano/south-conqueror/assets/38771873/5d92cc09-cb3b-4c53-b331-9ae8eb256c9a)

cuando entras al menu de ordenes de compra y elejis el ejemplo que te envio, se bloquea toda la pantalla

**Comment by sebasmoyano** [comment]
Esto es una mejora, un registro tiene muchos movimientos, podemos sacarlo a una acción. Confirmar.

**Comment by sebasmoyano** [comment]
Propuesto workaround.
