### ISSUE TITLE
Sistema Canteras - Menu de Stock de materiales

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#252]
se debe contar con un menu de stock de materiaes los cuales se va modificando permanentemente con los valores tomados desde el archivo que es trasmitido por request. tambien cada material debe contar con la opcion carga manual, que solo los administradores deben tener.
acordate que cada material esta asociado a una cantera, y se puede mover o hacer como una especia de movieinto de stock a otra cantera.
en el menu de movimiento de produccion debe estar asociado si o si a un numero de remito.

**Comment by sebasmoyano** [comment]
Esto ya se maneja. Por favor leer los correos. Estás tomado por los servicios de niñero.

> Agregué el módulo de manejo de producción:
> Plantas
> Productos: manejan un tipo para saber si es materia prima o comercial y guardan el stock actual en toneladas.
> Líneas de producción: es lo que llaman  layout de producción. Tiene la configuración de cada línea de producción por planta. Se considera el producto de input (no obligatorio) y los productos de salida. Se setean las proporciones.
> Movimientos de producción: registros de cada ingreso a la línea de producción basado en una línea de producción. Llenará automáticamente los campos con las proporciones, es configurable.

**Comment by casma20** [comment]
ya se que se hace, pero este menu es para la forma manual del manejo, hay que crear otro para cuando llegue el archivo y coloquemos los datos en forma automatica vergoglio.
