### ISSUE TITLE
SanFernando - Sistema de Ordenes - pago de fletes

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#27]
Seba hay un error en el sistema de ordenes, te deja cargar 2 pagos de fletes con el mismo numero de remito, en relidad el numero de remito es **unico** lo que puede llevar es 2 o mas facturas asociadas.

**Comment by sebasmoyano** [comment]
@casma20 Ahora el Número de remito es único en el pago de fletes.
