### ISSUE TITLE
Mica - Camión Club - Impresión de ticket - Detalle a mostrar

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#28]
Seba fijate si podemos agregarle al ticket la informacion de la patente del camion  y la estadia del camion detallados.

**Comment by sebasmoyano** [comment]
@casma20 creado issue separado para modificar la cantidad manual. Por favor no mezclar tareas.

**Comment by casma20** [comment]
no, solo imprime la estadia. no dice la patente

**Comment by sebasmoyano** [comment]
![ticket](https://user-images.githubusercontent.com/5084534/40399886-0cffc00c-5e16-11e8-8f3d-264b804b13eb.png)

No entiendo lo que falta.

**Comment by sebasmoyano** [comment]
@casma20 agregado patente y patente acoplado al costado del nombre del cliente. Puede cortarse porque permite solo 30 caracteres.
