### ISSUE TITLE
Mica - Camión Club - Impresión comienza a fallar luego de un tiempo

### ISSUE THREAD

**Issue by sebasmoyano** [sebasmoyano/south-conqueror#3]
La impresión deja de funcionar luego de un tiempo.

**Comment by sebasmoyano** [comment]
@casma20 puse un cambio y fijate ahí.

**Comment by sebasmoyano** [comment]
@casma20 necesito los logs.

**Comment by sebasmoyano** [comment]
@casma20 parece ser un problema de conexión. Por eso no he visto el error y a vos a veces te pasa y a veces no.

**Comment by sebasmoyano** [comment]
También podés probar con Chrome 65. Me funciona sin problemas.

**Comment by casma20** [comment]
![image](https://user-images.githubusercontent.com/38771873/40280319-91dbdb08-5c27-11e8-9f83-47351d292332.png)
seba estoy probando facturar en mi casa y no anda....

**Comment by casma20** [comment]
![image](https://user-images.githubusercontent.com/38771873/40284618-0ab95aa6-5c68-11e8-9487-fb0af2afaf9f.png)

SEBA NO PUEDEN INGRESAR LOS MISMOS CAMIONES, SIN SACARLOS. si o si hay que sacarlo y despues volverlo a entrar. eso esta mal

**Comment by sebasmoyano** [comment]
Parece ser un problema de correr la versión vieja/nueva en la misma máquina. Verificar probando desde cero.

**Comment by sebasmoyano** [comment]
Creado issue https://github.com/sebasmoyano/south-conqueror/issues/29 para manejar lo que reportaste. Por favor abrir issues nuevos cuando se tratan de cosas diferentes.

**Comment by sebasmoyano** [comment]
@casma20 dale una probadita, arreglé un error extraño que puede estar relacionado a este issue.

**Comment by sebasmoyano** [comment]
@casma20 cerramos este issue?

**Comment by sebasmoyano** [comment]
@casma20 cerramos este issue?

**Comment by sebasmoyano** [comment]
@casma20 como no hay respuesta lo cierro....
