### ISSUE TITLE
San Fernando - Órdenes - Mejoras totales reportes

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#33]
![image](https://user-images.githubusercontent.com/38771873/40431111-1b00e8ea-5e7d-11e8-99b1-09ae8081154f.png)

Seba todos los totales grandes, salen asi de desordenado seba fijate en agrandarle las columnas o sacarles ceros despues de las comas

**Comment by sebasmoyano** [comment]
@casma20 Mejorado todos los totales en cada reporte del sistema de órdenes. En algunos casos se agregaron totales. Ahora existe una nueva tabla que sumariza totales.
