### ISSUE TITLE
SGA - Sistema Arenas - Nueva sección de Reportes

### ISSUE THREAD

**Issue by sebasmoyano** [sebasmoyano/south-conqueror#34]
Nueva sección de reportes que permita:
- Consultar viajes.
- Consultar facturas.

**Comment by casma20** [comment]
agregale un reporte de facturas seba porque me lo va a pedir

**Comment by sebasmoyano** [comment]
@casma20 implementado esto. Por ahora no lo cierro por si piden nuevos filtros o columnas.

**Comment by sebasmoyano** [comment]
@casma20 cerrando esto que ya se implementó y no se obtuvo feedback-
