### ISSUE TITLE
San Fernando - Impresion de Ordenes

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#36]
Seba cuando son pocas las ordenes a listar, y mandas a imprimir, los totales salen en otra pagina y no en la misma pagina del listado. osea si vas a listar 5 ordenes de carga y entra perfectamente en una hoja, los totales se imprimen en otra en vfes de la misma.

quiere ahorrarce una hoja.....

**Comment by sebasmoyano** [comment]
Como quedamos es un tema del framework que manda a otra hoja.
