### ISSUE TITLE
Mica - Camión Club - Reporte egresos > agregar filtro por empresa

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#37]
Seba me estas debiendo agregar el filtro por EMPRESA  al reporte de ingresos y egresos.

**Comment by sebasmoyano** [comment]
Reportar más prolijo por favor.

**Comment by sebasmoyano** [comment]
Poner tareas separadas cuando son cosas diferentes.

**Comment by sebasmoyano** [comment]
@casma20 agregado filtro y mejorado styling.
