### ISSUE TITLE
San Fernando - Órdenes - Reporte órdenes pendientes

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#39]
seba necesito un nuevo reporte de ordenes pendientes, que los liste con todos sus datos. y los imprima.

**Comment by sebasmoyano** [comment]
@casma20 Se realizaron las siguientes tareas:
- Agregado reporte de órdenes pendientes.
- Estandarizado formateo de los valores del tipo dinero: 2 decimales y separador de miles.
- Mejorado styling.
- Agregado número de página en el footer.
