### ISSUE TITLE
Mica- Camión club - Facturación manual

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#42]
Sigue sin andar cuando cambio el importe manual en la factura y lo envio a imprimir, no pasa nada....se queda trabado. ahora cuando le invento una fecha de entrada para tratar de llegar al importe requerido, la factura sale correctamente.

**Comment by sebasmoyano** [comment]
@casma20 probé y envía bien la info al gestor de impresiones. Podés dar más información? Qué mandás en el request, qué campos modificás? Qué le llega al gestor de impresiones?

**Comment by sebasmoyano** [comment]
Cerrando por no recibir feedback.
