### ISSUE TITLE
Mica - Estacionamiento - Facturación automática

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#44]
1 cuando ingrese el camion en el MENU CREAR debe preguntarle que tipo de factura a relizar.

2 cuando el operador lo saque al camion a egreso, automaticamente le sale un popup preguntandole si realmente lo quiere facturar, asi le da la opcion a volverlo a ingresar si es un  error.

3 tener en cuenta que pasa cuando la impresora fiscal se queda sin papel....como se puede hacer en ese caso para reimprimir, y lo mismo para cuando se corta la luz y el camion se tiene que ir al choto y sigue ingresado en el sistema.....

**Comment by sebasmoyano** [comment]
@casma20 cerrando esto hasta que haya una decisión.
