### ISSUE TITLE
Mica - Estacionamiento - Facturación en grupo 

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#45]
1 crear un menu nuevo al usuario con permisos, que pueda seleccionar empresa y grupos de sus camiones.

2 una ves asignado cada grupo de facturacion, los operadores NO  pueden facturar los camiones sino que se guardan en un menu cada uno con su estadia y el importe.

3 el administrador tiene derecho a modificar el importe de la estadia, concepto y precio antes de facturar por camion.

4 se podria crear un reporte de facturacion por grupos.

**Comment by sebasmoyano** [comment]
@casma20 cerrando esto hasta que haya una decisión.
