### ISSUE TITLE
Mica - Reporte de Facturacion

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#49]
seba otra ves se vuelve a repetir el error de que cuando se genera una nota de credito, se replica en todos los usuarios y les resta a la hora de emitir el reporte la nota de credito. por ejemplo si sacas un reporte del dia 02/07 de 6 de la mañana a14hs el usuario oscar velazques genera una nota que le pertenece y cuando emite su facturacion esta bien que le reste ese faltante.

pero si sacas al turno siguiente de 14 a 22 hs el usuario ruben vivas emite el reporte y le sale la misma nota y el culeado se descuenta la guita!!!!!! y no la envia. Habiamos quedado que solo aparecia la nota de credito en el turno del usuario que facturaba en ese momento. o de ultima habra que asociar a la hora de hacer la nota, a quien o a que turno le pertenece la nota, asi  deja de aparecer replicados en todos los usuarios.

**Comment by sebasmoyano** [comment]
Arreglado Casma. Tenés que asignar el usuario del turno a la nota para que filtre. También arreglé las fechas de las notas en el reporte que no salía bien.
