### ISSUE TITLE
Sistema de Mensajeria Interna MICA SA

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#50]
el programa es que toda idea, conversacion o cualquier tipo de informacion interna sea administrada por el programa y compartida por todos los usuarios participantes. a una escala de roles como si fuera un arbol. el que esta en la cima se entera de todo el puterio.
ya existe un programa asi y lo quieren encajar a la fuerza....oviamente yo le dije que lo desarrollamos y lo incorporamos al sistema actual. asi que afinale al lapiz seba y le metemos. te paso algunas capturas del otro sistema y de lo que deberia hacer el nuestro.
Estaria piola hacer todo lo que te mando. vos decime si se puede o no.
![screenshot_2018-08-15-20-48-31](https://user-images.githubusercontent.com/38771873/44536184-45d91e00-a6d2-11e8-98d2-ddf5b2cb9f7a.png)
![screenshot_2018-08-15-20-48-15](https://user-images.githubusercontent.com/38771873/44536191-4d98c280-a6d2-11e8-8c35-e65e0a6d1dcb.png)
![screenshot_2018-08-15-20-30-49](https://user-images.githubusercontent.com/38771873/44536205-52f60d00-a6d2-11e8-8418-0e130abea523.png)
![screenshot_2018-08-15-20-30-20](https://user-images.githubusercontent.com/38771873/44536220-57bac100-a6d2-11e8-869a-2903e42f32cf.png)
![screenshot_2018-08-15-20-27-24](https://user-images.githubusercontent.com/38771873/44536230-5db0a200-a6d2-11e8-88d4-ad00db9c8efd.png)
![screenshot_2018-08-15-20-26-43](https://user-images.githubusercontent.com/38771873/44536238-60ab9280-a6d2-11e8-8b31-32022b84d4b6.png)
![screenshot_2018-08-15-20-23-54](https://user-images.githubusercontent.com/38771873/44536243-64d7b000-a6d2-11e8-8306-7b93c99a88b6.png)
![screenshot_2018-08-15-20-24-01](https://user-images.githubusercontent.com/38771873/44536245-65704680-a6d2-11e8-81da-31a7d6b2ed67.png)

**Comment by sebasmoyano** [comment]
Con la plataforma se puede hacer algo integrando `Slack` que es un chat que se usa en entornos corporativos. 
Una integración con la plataforma te permitiría hacer cosas como escribir en el chat: `#nota llamar a Casma`. Eso crearìa una tarea en el sistema. 
Igual no sé si se justifica un desarrollo con las herramientas que existen.

**Comment by sebasmoyano** [comment]
Cerrando este ticket por inactividad.
