### ISSUE TITLE
Control de Flotas > Mejoras

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#51]
- agregar botones para crear y asi no salir de un formulario. ejemplo en unidades, si no tengo un tipo de auto, deberia tener el boton de agregar, lo mismo en la parte de marcas y todos los lugares que pedis ingreso de datos.

- El modelo en el menu de unidades es alfanumerico, no solo numeros.

- en donde pedis la vigencia de la poliza, deberia ser un calendario, no ingresarlo como el usuario quiera.

- a la hora de subir archivos, modificar que te deje subir mas de 2.

- el boton acciones no hace nada.

- en el menu principal cuando vas a una tarea y le das click con el mouse y pones acciones se queda cargando y no hace nada.

**Comment by sebasmoyano** [comment]
1. Por favor especificar cada sección con precisión. En el caso de las marcas, lo manejaríamos nosotros, no el usuario.
2. No se entiende.
3. Cambiado.
4. Cambiado para actividad vehículo.
5. Eso es un bug de la plataforma. Calculo que se arreglará pronto.
6. No se entiende.

Cerrando esto... Cualquier cosa abrite un issue separado.
