### ISSUE TITLE
Radatilly - formulario Clientes

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#56]
Seba el formulario clientes estaria demas, porque para ellos los clientes son los transportistas, que estan agrupados por grupos. asi que habria que sacarlo.

**Comment by sebasmoyano** [comment]
Fijate en las formularios que está la columna Cliente.  Ejemplos: Tecpetrol, YPF, etc.

**Comment by sebasmoyano** [comment]
Cerrando esto...
