### ISSUE TITLE
Radatilly - Formulario Grupo de Remitos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#57]
habria que crear el formulario grupo de remitos para asociar varios remitos a un DESTINO. la idea seria que una ves que ete creado el remito, selecciones cada uno de los remitos y se los asignes a un destino y aparescan como las facturas en proceso de sga. con los siguientes datos
 

remitos     fecha de grupo de remito    cliente     Destino    bolsones         peso bruto          tara          peso total

**Comment by sebasmoyano** [comment]
Implementado esto. Cerrando..
