### ISSUE TITLE
San Fernando - Ordenes - Errores

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#6]
1. No funciona el desplazamiento del menu para cargar el numero de formulario de gobierno, cuando se elige como destino cualquier Ceramica San lorenzo. 
2. No se carga el combo condiciones de pago en un operador.
3. En reportes liquidacion de fletes no se carga el combo origen.
4. En el combo a elegir el transportista y después el chofer y el camion, te trae todos los choferes y camiones en ves de traer los asociados a la empresa.

**Comment by sebasmoyano** [comment]
@casma20 
Arreglado 4 issues reportados.
