### ISSUE TITLE
Sistema de Ordenes Sanfernando - Reportes

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#62]
Seba los reportes en el sistema de ordenes no se estan mostrando y tampoco migra a Excel bien. generan un archivo dañado

**Comment by sebasmoyano** [comment]
Me funciona bien generarlo en PDF y en Excel no está implementado. 
Cerrando...

**Comment by sebasmoyano** [comment]
Chequeado y funciona bien.

**Comment by sebasmoyano** [comment]
Funciona bien el reporte de comisiones. Te envío el archivo.
