### ISSUE TITLE
San Fernando - Órdenes - Manejo de comisiones, tarifas, plantas y destinos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#7]
1. Manejar el concepto de destino aparte. Es un lugar y no una empresa.
2. Manejar el concepto de planta aparte. Es un lugar y no una empresa.
3. Las comisiones se calculan por planta. Ejemplo DOLAVON 5%, ARDON 3%, MOLIENDA TANDILIA 4%. 
4. Manejo de cuadro tarifario. La tarifa varía según planta y destino. 
5. Un operador no debe visualizar comisiones.
6. En reportes órdenes de carga en vez de destino se debe elegir el combo origen.

**Comment by sebasmoyano** [comment]
@casma20 separé el issue en 2.

**Comment by sebasmoyano** [comment]
@casma20 
Casma está listo el manejo de comisiones, tarifas, plantas y destino. Cerrando...
