### ISSUE TITLE
Rada Tilly > Workflow de estados remitos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#71]
ACORDATE QUE FALTA CREAR ESTADOS EN EL REMITO

PENDIENTE-FACTURADO-RECHAZADO

**Comment by sebasmoyano** [comment]
@casma20 estados:
- Pendiente: al crear el remito. Un remito pendiente puede ser facturado.
- Anulado: acción disponible.
- Observado: acción disponible. Se setea un nuevo pesaje bruto. Un remito observado puede ser facturado.
- Facturado: Se setea cuando se realiza la facturación.
