### ISSUE TITLE
Radatilly- Menu de facturación (TBD)

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#76]
- Habilitar el dato de cantidad facturada , que difiere de la cantidad enviada por diferencias en pesos de balanza en el destino.

**Comment by casma20** [comment]
Adentro del menu facturacion, a la hora de cargar el numero d e factura, rellenalo de ceros.

**Comment by sebasmoyano** [comment]
- Manejar el estado `Anulado`. Nueva acción.

**Comment by casma20** [comment]
Seba falta el campo de material en el formulario de facturacion, acordate que es razon social...destino...material, y los precuis son por toneladas de materiales

**Comment by sebasmoyano** [comment]
Una factura puede tener N remitos. Por lo que el material puede diferir. Analizar mejor.
