### ISSUE TITLE
Radatilly - Cuadro tarifario en USD

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#77]
los campos del formulario serian serian:

Razon social, destino, tipo de material material, y precio en USD ( en DOLARES )

El formulario debe tener un campo de ingreso de cotizacion actual del dolar, y poder transformarlo a pesos en el reporte de facturacion y en la factura, pero en el formulario se carga en dolares.

**Comment by sebasmoyano** [comment]
La cotización es variable. Quién la va a actualizar todos los días? Las facturas existentes se actualizan cuando cambia la cotización?

**Comment by casma20** [comment]
el administrador de comodoro, vos generales los campos como quieren. y que s emanejen

**Comment by sebasmoyano** [comment]
@casma20 
Se implementó esto. Hay una nueva propiedad en `Propidades del sistema` llamada `Cotización del dólar`. Se toma ese valor de referencia a la hora de facturar. Es modificable en el form de facturación.
