### ISSUE TITLE
Radatilly - Modificaciones reportes

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#78]
**Reporte remitos:**
- Filtrar por  ORDEN DE COMPRA y mostrar los remitos asociados.
- Necesitamos que el campo GRUPO DE TRANSPORTISTAS sea designado como filtro.

**Reporte facturación:**
- En los reportes también tiene que figurar el cuadro tarifario.

**Comment by sebasmoyano** [comment]
@casma20 
- Agregado filtro orden de compra.
- Agregado filtro grupo transportista.
- Agregada columna orden de compra en remitos.

**Comment by sebasmoyano** [comment]
> Reporte facturación: en los reportes también tiene que figurar el cuadro tarifario.
No se puede configurar una sola tarifa ya que cada remito puede ir a un destino diferente. Hay que analizar mejor esto.
