### ISSUE TITLE
Radatilly - Roles de Usuarios

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#79]
**Rol: Operador Dolavon**
soraya.reyes@transportesradatilly.com.ar
claudia.cervinio@transportesradatilly.com.ar
lorena.erise@transportesradatilly.com.ar

**Permisos:**
impresion de remito
remitos en proceso
remitos
logistica 
parametros

**Comment by casma20** [comment]
administradores de dolavon
paula.sanchezcordi@transportesradatilly.com.ar

Permisos
TODOS LOS MENUS MENOS FACTURACION
impresion de remitos
remitos en el proceso 
remitos 
logisticos 
parametros
Reportes todos MENOS FACTURACION

**Comment by casma20** [comment]
administracion comodoro
romina.ramos@transportesradatilly.com.ar
Permisos
cuadro tarifario
facturacion
reportes (solo la parte de facturacion)
logistica 
parametros

**Comment by casma20** [comment]
paola.altamirano@transportesradatilly.com.ar

Permisos 
cuadro tarifario 
facturacion 
reportes (solo la parte de facturacion) 
logistica 
parametros

**Comment by sebasmoyano** [comment]
Creados roles:
```
- Operador Dolavon
- Administrador Dolavon
```

`Administrador comodoro` es perfil `Administrador`  ya que necesita tener acceso a los remitos.
