### ISSUE TITLE
Radatilly - Remitos - Manejo de número de remito

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#80]
Crear un campo que solo los administradores pueden modificar y ver, que permita asignarle el numero del remito y apartir de ahi se genere automaticamente.
No quieren que el usuario ingrese el numero manual, sino que sea administrado por sistema.
Acordate que el formulario ya tiene pre impreso el numero asi que el sistema solo lo administraria. 

es todo un tema el campo del numero de remito porque hay varios factores que manejar y que pueden fallar.
1 el usuario ingresa mal el numero.
2 el usuario ingresa bien el numero pero pone mal el fisico en impresora (otro numero).
3 el fisico viene modificado.

creo que la mejor manera es que solo un usuario administrador en este caso paula.sanchezcordi@transportesradatilly.com.ar sea la encargada de modificar e iniciar el proceso de carga del numero de remito.

**Comment by sebasmoyano** [comment]
@casma20 se implementó esto.
Ahora hay una nueva sección ubicada en `Parámetros > Propiedades del Sistema`. Ahí se configura el número inicial del remito. Sólo un usuario `Administrador` podrá cambiar el número de remito para el resto de los perfiles será de sólo lectura.
