### ISSUE TITLE
Radatilly - Remitos Observados

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#81]
al abrir el formulario de observacion de remitos, hay que cambier:
Nuevo peso NETO, no bruto
y cambiar tambien la cantidad de bolsones.

**Comment by sebasmoyano** [comment]
Agregar bolsones nada más.

**Comment by sebasmoyano** [comment]
Prioridad 3.

**Comment by sebasmoyano** [comment]
@casma20 se agregó el campo cantidad bolsones.
