### ISSUE TITLE
Radatilly - Impresión de remito resumen

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#82]
a la hora de imprimir el remito grupo. los campos a imprimir serian:

-     fecha
-     razon social
-     destino
-     cuit
-     localidad
-     n° orden de compra
-     hora de carga
-     catidad de bolson (se imprimiria cantidad de numero de remito)
-     descripcion (se imprimiria los numeros de remitos asociados)
-     peso bruto (la suma de todos los remitos)
-     tara (la suma de todos los remitos)
-     peso neto (la suma de todos los remitos)

quedarian completar con la misma imformacion siempreeeeee que se imprima:    

- **transporte:**    TRANSPORTES RADA TILLY SA
-     **chofer:**       RUMIPILLAN CARLOS 
-     **dominio:**    AA500BB-AA263ZU 
-     **n° lote:**       0

**Comment by sebasmoyano** [comment]
Prioridad 1

**Comment by sebasmoyano** [comment]
Remitos resumen: razón social y destino.  Orden separada por comas.

**Comment by sebasmoyano** [comment]
@casma20 implementado este feature.
