### ISSUE TITLE
Radatilly - Nuevo remito desde Filomena

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#84]
Desde la filomena, neuquen, emiten un remito exactamente igual que el que nosostros imprimimos, pero se recepciona aca en Dolavon y se cargan los datos nada mas, tiene los mismos campos que el remito que manejamos nosotros. 
Habria que generar un formulario exactamente igual para la carga o en el menu de carga del formulario actual diferenciar por puntos de Venta. en el caso de dolavon es el numero 5 y la filomena 7.

- 1.  Entonces crearia un menu de Puntos de Venta porque si van a seguir agregando datos para el futuro...es mejor manejarlo.
- 2.  A la hora de cargar el formulario, diferenciar la carga de puentos de venta, dejando por defecto DOLAVON.

3 Solo puede cargar los datos de este formulario paula.sanchezcordi@transporteradatilly.com.ar, las demas personas son como burros de arado....

**Comment by sebasmoyano** [comment]
@casma20 
Se implementó este nuevo remito que se carga de una todo a la vez, a diferencia de los registros de remitos de Dolavon.

Existe una nueva sección llamada `Puntos de Venta`. `Remitos` y `Remitos en proceso` configuran por defecto el punto de venta Dolavon.

Solo los administradores ven la sección `Remitos Filomena`.
