### ISSUE TITLE
Radatilly - Usuarios de sistema

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#86]
seba reseteame el usuario claudia.cervinio@transportesradatilly.com.ar

ponele de pas Claudia1234

porque los email no existen...

**Comment by sebasmoyano** [comment]
Tienen que usar un email que exista porque no puedo estar reseteando. Creale cuentas en gmail a todos.

**Comment by sebasmoyano** [comment]
Se lo reseteé.
