### ISSUE TITLE
Radatilly - Menu de remitos en procesos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#89]
Cuando se acumulan los remitos en procesos, no hay una accion para archivarlos, sino de eliminar. y si lo eliminan se borra de todos lados, no solo de la pantalla

**Comment by sebasmoyano** [comment]
Hasta que no lo factures van a estar ahì. Se puede considerar un estado intermedio pero no lo recomiendo.

**Comment by casma20** [comment]
Los numeros de remito no inician de donde lo deja el administrador
ejemplo: 0005-00027810

![errornumremito](https://user-images.githubusercontent.com/38771873/49378079-88a38c80-f6ea-11e8-9a07-79af4ff55008.jpg)

**Comment by casma20** [comment]
Pasa que se hace un listado y estos cabezas de tarro se ponen a pelotudear y pueden borrar alguno...
