### ISSUE TITLE
Radatilly - Formularios

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#91]
A la Hora de agregar un dato cuando no se encuentra en el sistema, ya sea camion o chofer desde el formulario de carga de remitos (cualquiera sea) te tira un error que el dato no es correcto.

tenes que salir....y cargar el dato que te hace falta desde el menu logistica

![erro_carga](https://user-images.githubusercontent.com/38771873/49377449-f949a980-f6e8-11e8-9aed-6bd75311f04d.jpg)

**Comment by sebasmoyano** [comment]
@casma20 lo revisé y funciona bien. Para que funcione correctamente tenés llenar el campo `Transporte` y luego crear el camión. Acordate que el campo `Empresas de servicio` del camión tiene que coincidir con el campo `Transporte`.
