### ISSUE TITLE
Radatilly - Puntos de Venta

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#92]
No me deja editar los puntos de venta, cambiarle la localidad ni provincia, y la idea era que cuando ingresamos al menu de carga de remito, elijas el punto de venta, por defecto tiene que ser DOLAVON pero como los datos a ingresar son los mismos, a la hora de cargar, deberia dejarte elejir el punto de venta.

segun que punto de venta, es como lo vamos a listar por reportes seba. el menu de remitos filomena esta al pedo me parece. 
deberias tener un campo mas en el menu de remitos de punto de venta asi queda ordenado y listado.

**Comment by sebasmoyano** [comment]
OK. No estaba claro el requerimiento anterior. Por favor no copiar y pegar lo que te dicen ellos. Masticarlo un poco antes de reportar un issue.

**Comment by casma20** [comment]
chupame la pijota...a vos se te ocurrio la idea del punto de venta chevin...ja
