### ISSUE TITLE
Radatilly - Carga de Remitos

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#93]
Cuando entras a cargar directamente el remito no te deja ingresar el numero de remito.
![errorremito](https://user-images.githubusercontent.com/38771873/49378759-29467c00-f6ec-11e8-8e83-70aef9221dd0.jpg)

**Comment by sebasmoyano** [comment]
Es correcto porque el remito debe estar en Pendiente. Se puede cambiar si se desea.
