### ISSUE TITLE
Radatilly - Ordenes de Carga

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#94]
No hay permisos para editar toneladas las ordenes.

![errorordeneditar](https://user-images.githubusercontent.com/38771873/49379519-0cab4380-f6ee-11e8-8f57-0e2d13cee3f1.jpg)

**Comment by sebasmoyano** [comment]
Leer los **comentarios** cuando un issue es cerrado.

**Comment by casma20** [comment]
jajajajajjaja no lo vi...sorry
