### ISSUE TITLE
Radatilly - Resumen Remito

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#95]
Cambios a realizar:

- Cargar a mano el numero de remito, con alguna letra diferenciando que es un Numero de Resumen ejemplo RR 0005-000030458 asi se les hace mas facil a la hora de facturar, 

- Debe asociar el numero de orden de carga correspondiente, vos ahora lo estas enviando a imprimir pero no figura en el sistema en ningun lado.
- La impresión del remito debe salir con los numero de remitos ordenados, si te fijas son varios remitos asociados y hasta ahora salen impresos en linea, y no entran en el papel fisico

**Comment by sebasmoyano** [comment]
@casma20 Implementado cambios requeridos
