### ISSUE TITLE
Radatilly - Conversion a Excel 

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#98]
les mande el ejemplo que te tira el sistema cuando convierte a excel a los de soporte de microsoft y me respondieron que para que sea compatible con todas las verciones modifiques las llamadas a cabeceras.

![image](https://user-images.githubusercontent.com/38771873/49459627-3b005000-f7ce-11e8-9546-64433510df60.png)

**Comment by casma20** [comment]
cabeceras:

<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:html="http://www.w3.org/TR/REC-html40">
    <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
        <Version>14.00</Version>

**Comment by casma20** [comment]
cabeceras:
![image](https://user-images.githubusercontent.com/38771873/49459848-c11c9680-f7ce-11e8-89d0-fd75444874bf.png)

**Comment by sebasmoyano** [comment]
podrías haber copiado las cabeceras en texto jeje.

**Comment by sebasmoyano** [comment]
Cambiado. Funciona bien en LibreOffice.
