### ISSUE TITLE
Radatilly - Oreden de Carga- Debe restar Peso Neto

### ISSUE THREAD

**Issue by casma20** [sebasmoyano/south-conqueror#99]
Seba esta restando mal las toneladas, debe restar al STOCK de toneladas el PESO NETO y el sistema esta restando el PESO BRUTO.

![image](https://user-images.githubusercontent.com/38771873/49467917-4eb5b180-f7e2-11e8-9429-635d798e4658.png)

**Comment by sebasmoyano** [comment]
Arreglado.
